export type Project = {
  slug:string; name:string; category:string; summary:string; challenge:string; solution:string; features:string[]; url?:string; sector:string; status:string;
};

export const projects: Project[] = [
  {slug:"soveuro",name:"Sociedad Venezolana de Urología",category:"Salud · Web institucional",sector:"Salud",status:"Plataforma institucional",summary:"Ecosistema digital para contenido científico, documentos, noticias y vinculación con miembros.",challenge:"Centralizar la presencia institucional y facilitar el acceso a información científica, actividades y recursos profesionales.",solution:"Una plataforma corporativa organizada por contenidos y servicios, conectada con el ecosistema digital de la sociedad.",features:["Web institucional","Contenido científico","Recursos para miembros","Noticias y actividades","Integración con SoveuroApp"],url:"https://soveuro.org/"},
  {slug:"soveuroapp",name:"SoveuroApp",category:"Salud · Membresías y eventos",sector:"Salud",status:"Sistema de gestión",summary:"Plataforma para colegiatura, afiliación, pagos, eventos, tickets y control mediante QR.",challenge:"Digitalizar la relación operativa entre la sociedad médica, sus miembros y los eventos científicos.",solution:"Un sistema integrado de membresías, pagos, solvencias, entradas y validación que reduce procesos dispersos.",features:["Gestión de miembros","Colegiatura y pagos","Eventos y tickets","Escaneo QR","Panel administrativo"],url:"https://soveuroapp.com/"},
  {slug:"sociedad-venezolana-cardiologia",name:"Sociedad Venezolana de Cardiología",category:"Salud · Colegiatura",sector:"Salud",status:"Membresías profesionales",summary:"Aplicación para gestionar membresías profesionales, colegiatura y participación en eventos.",challenge:"Organizar el registro profesional, el estado de colegiatura y la interacción con actividades científicas.",solution:"Una experiencia centralizada para miembros y administradores con acceso a procesos esenciales de la organización.",features:["Afiliaciones","Membresías","Colegiatura","Eventos","Panel de gestión"],url:"https://appsvc.drbriones.com/#/membership"},
  {slug:"zoriapp",name:"ZoriApp",category:"HealthTech · Jornadas masivas",sector:"Salud",status:"PWA operativa",summary:"Gestión operativa y estadística de jornadas de despistaje de cáncer de próstata.",challenge:"Coordinar pacientes, estaciones y datos clínicos durante jornadas de atención con alto volumen de participantes.",solution:"Una PWA que estructura el recorrido operativo, centraliza registros y facilita la consolidación de información de la jornada.",features:["Registro de pacientes","Flujo por estaciones","Captura de datos","Reportes operativos","Instalación PWA"],url:"https://zoriapp.vercel.app/"},
  {slug:"pacigest-plus",name:"PaciGest Plus",category:"HealthTech · Consultorios",sector:"Salud",status:"Sistema administrativo",summary:"Plataforma para organizar pacientes, consultas, agenda y operación administrativa de consultorios.",challenge:"Reducir la fragmentación de la información y simplificar la gestión cotidiana del profesional de salud.",solution:"Un entorno centralizado para administrar pacientes, agenda, consultas y tareas administrativas.",features:["Pacientes","Agenda","Consultas","Gestión administrativa","Experiencia responsive"],url:"https://pacigestplus.com/"},
  {slug:"citaclick",name:"CitaClick",category:"Servicios · Reservas",sector:"Servicios",status:"Producto digital",summary:"Solución de citas y reservas orientada a profesionales y empresas de servicios.",challenge:"Disminuir la fricción de coordinar horarios mediante conversaciones manuales y agendas dispersas.",solution:"Una experiencia de reservas en línea con disponibilidad, solicitudes y gestión de clientes.",features:["Reservas en línea","Disponibilidad","Confirmaciones","Gestión de clientes"]},
  {slug:"mesaclick",name:"MesaClick",category:"Gastronomía · Experiencia digital",sector:"Comercio",status:"Experiencia para restaurantes",summary:"Plataforma para conectar mesas, menús y servicios digitales en restaurantes.",challenge:"Facilitar el acceso inmediato a información comercial y mejorar la interacción del cliente en el establecimiento.",solution:"Una experiencia móvil vinculada a la mesa mediante enlaces, QR o NFC, preparada para catálogos y promociones.",features:["Menú digital","Acceso por mesa","Promociones","Experiencia móvil"],url:"https://mesaclick.vercel.app/"},
  {slug:"lider-seguros-nfc",name:"Líder Seguros NFC",category:"Seguros · Movilidad",sector:"Seguros",status:"Portal conectado por NFC",summary:"Portal conectado con llaveros NFC para pólizas, asistencia, documentos y mantenimiento vehicular.",challenge:"Mantener servicios y documentos relevantes disponibles para el asegurado desde un punto de acceso permanente.",solution:"Un llavero NFC conectado a un portal vehicular que concentra asistencia, pólizas y utilidades del vehículo.",features:["Acceso NFC","Pólizas y documentos","Asistencia vial","Mantenimiento vehicular"],url:"https://liderseguros.vercel.app/"},
  {slug:"elite-links",name:"Elite Links",category:"Movilidad · Portal inteligente",sector:"Movilidad",status:"Portal de servicios",summary:"Portal de servicios vehiculares, emergencias, aliados, documentos y recordatorios.",challenge:"Unificar accesos críticos y beneficios del conductor en una sola experiencia digital.",solution:"Un portal adaptable conectado por enlace o NFC con servicios, documentos y aliados organizados por prioridad.",features:["Emergencias","Aliados","Documentos","Mantenimiento","Promociones"],url:"https://elite-links.vercel.app/"},
  {slug:"guia-kupai",name:"Guía Kupai",category:"Comercio · Directorio digital",sector:"Comercio",status:"Directorio comercial",summary:"Directorio y guía digital para conectar consumidores con comercios y opciones gastronómicas.",challenge:"Facilitar el descubrimiento de negocios y organizar la oferta comercial por categorías.",solution:"Una guía móvil con navegación directa hacia comercios, categorías y propuestas disponibles.",features:["Directorio","Categorías","Experiencia móvil","Enlaces comerciales"],url:"https://guia.kupaifastfood.com/"},
];
