export type Project = {
  slug: string;
  name: string;
  category: string;
  summary: string;
  challenge: string;
  solution: string;
  features: string[];
  url?: string;
  sector: string;
  status: string;
  image?: string;
  imageAlt?: string;
  accent: "cyan" | "pink" | "gold" | "violet" | "lime";
};

export const projects: Project[] = [
  {
    slug: "soveuro",
    name: "Sociedad Venezolana de Urología",
    category: "Salud · Web institucional",
    sector: "Salud",
    status: "Plataforma institucional",
    summary: "Ecosistema digital para contenido científico, documentos, noticias y vinculación con miembros.",
    challenge: "Centralizar la presencia institucional y facilitar el acceso a información científica, actividades y recursos profesionales.",
    solution: "Una plataforma corporativa organizada por contenidos y servicios, conectada con el ecosistema digital de la sociedad.",
    features: ["Web institucional", "Contenido científico", "Recursos para miembros", "Noticias y actividades", "Integración con SoveuroApp"],
    url: "https://soveuro.org/",
    image: "/projects/soveuro.png",
    imageAlt: "Portada de la plataforma de la Sociedad Venezolana de Urología",
    accent: "gold",
  },
  {
    slug: "soveuroapp",
    name: "SoveuroApp",
    category: "Salud · Membresías y eventos",
    sector: "Salud",
    status: "Sistema de gestión",
    summary: "Plataforma para colegiatura, afiliación, pagos, eventos, tickets y control mediante QR.",
    challenge: "Digitalizar la relación operativa entre la sociedad médica, sus miembros y los eventos científicos.",
    solution: "Un sistema integrado de membresías, pagos, solvencias, entradas y validación que reduce procesos dispersos.",
    features: ["Gestión de miembros", "Colegiatura y pagos", "Eventos y tickets", "Escaneo QR", "Panel administrativo"],
    url: "https://soveuroapp.com/",
    image: "/projects/soveuroapp.png",
    imageAlt: "Interfaz de acceso de SoveuroApp",
    accent: "cyan",
  },
  {
    slug: "sociedad-venezolana-cardiologia",
    name: "Sociedad Venezolana de Cardiología",
    category: "Salud · Colegiatura",
    sector: "Salud",
    status: "Membresías profesionales",
    summary: "Aplicación para gestionar membresías profesionales, colegiatura y participación en eventos.",
    challenge: "Organizar el registro profesional, el estado de colegiatura y la interacción con actividades científicas.",
    solution: "Una experiencia centralizada para miembros y administradores con acceso a procesos esenciales de la organización.",
    features: ["Afiliaciones", "Membresías", "Colegiatura", "Eventos", "Panel de gestión"],
    url: "https://appsvc.drbriones.com/#/membership",
    image: "/projects/sociedad-venezolana-cardiologia.png",
    imageAlt: "Aplicación de membresías de la Sociedad Venezolana de Cardiología",
    accent: "pink",
  },
  {
    slug: "uroapp",
    name: "UroApp",
    category: "HealthTech · Uro-oncología",
    sector: "Salud",
    status: "En desarrollo",
    summary: "Registro clínico uro-oncológico para centralizar pacientes, triaje, historia clínica, estudios, tratamientos y seguimiento.",
    challenge: "Convertir un proceso clínico especializado y sensible en una experiencia clara para urólogos, oncólogos, residentes y equipos institucionales.",
    solution: "Una plataforma clínica responsive con acceso por roles, trazabilidad, perfil longitudinal del paciente, indicadores y flujos estructurados de atención.",
    features: ["Registro de pacientes", "Triaje uro-oncológico", "Historia clínica", "Estudios y tratamientos", "Agenda y reportes", "Acceso institucional"],
    image: "/projects/uroapp.png",
    imageAlt: "Propuesta de interfaces clínicas de UroApp para escritorio y tablet",
    accent: "lime",
  },
  {
    slug: "congreso-urologia-2026",
    name: "Congreso Venezolano de Urología 2026",
    category: "Salud · Experiencia de evento",
    sector: "Salud",
    status: "Programa digital interactivo",
    summary: "Digitalización del programa científico del XXXVI Congreso Venezolano de Urología en una experiencia web navegable.",
    challenge: "Organizar una agenda científica extensa, ponentes, sedes, actividades sociales e inscripciones sin depender únicamente de un PDF.",
    solution: "Un sitio editorial e interactivo que transforma el programa oficial en una experiencia accesible desde cualquier dispositivo.",
    features: ["Agenda científica", "Ponentes", "Sedes", "Inscripciones", "Aliados comerciales", "Descarga del programa"],
    url: "https://congreso2026-azure.vercel.app/",
    image: "/projects/congreso-2026.png",
    imageAlt: "Experiencia digital del Congreso Venezolano de Urología 2026",
    accent: "gold",
  },
  {
    slug: "fc-care-ai",
    name: "FC Care AI",
    category: "HealthTech · IA terapéutica",
    sector: "Salud",
    status: "En desarrollo",
    summary: "Aplicación móvil de acompañamiento terapéutico que conecta tratamiento, progreso clínico, bienestar y orientación personalizada mediante inteligencia artificial.",
    challenge: "Ayudar al paciente a comprender y sostener su tratamiento, registrar señales relevantes y convertir su seguimiento cotidiano en información útil para una atención más oportuna.",
    solution: "Un ecosistema móvil para pacientes de FC Pharma con onboarding clínico, control de dosis e inventario, evolución visual, registro guiado de síntomas y una asistente de IA accesible por texto o voz.",
    features: ["Adherencia al tratamiento", "Progreso clínico", "Bienestar personalizado", "Registro de síntomas", "Asistente IA por texto y voz", "Educación y beneficios"],
    image: "/projects/fc-care-ai.png",
    imageAlt: "Dashboard del paciente de FC Care AI con tratamiento, progreso, bienestar y asistente inteligente",
    accent: "lime",
  },
  {
    slug: "zoriapp",
    name: "ZoriApp",
    category: "HealthTech · Jornadas masivas",
    sector: "Salud",
    status: "PWA operativa",
    summary: "Gestión operativa y estadística de jornadas de despistaje de cáncer de próstata.",
    challenge: "Coordinar pacientes, estaciones y datos clínicos durante jornadas de atención con alto volumen de participantes.",
    solution: "Una PWA que estructura el recorrido operativo, centraliza registros y facilita la consolidación de información de la jornada.",
    features: ["Registro de pacientes", "Flujo por estaciones", "Captura de datos", "Reportes operativos", "Instalación PWA"],
    url: "https://zoriapp.vercel.app/",
    image: "/projects/zoriapp.png",
    imageAlt: "Pantalla de acceso de ZoriApp",
    accent: "violet",
  },
  {
    slug: "pacigest-plus",
    name: "PaciGest Plus",
    category: "HealthTech · Consultorios",
    sector: "Salud",
    status: "Sistema administrativo",
    summary: "Plataforma para organizar pacientes, consultas, agenda y operación administrativa de consultorios.",
    challenge: "Reducir la fragmentación de la información y simplificar la gestión cotidiana del profesional de salud.",
    solution: "Un entorno centralizado para administrar pacientes, agenda, consultas y tareas administrativas.",
    features: ["Pacientes", "Agenda", "Consultas", "Gestión administrativa", "Experiencia responsive"],
    url: "https://pacigestplus.com/",
    image: "/projects/pacigest-plus.png",
    imageAlt: "Portada de la plataforma de gestión médica PaciGest Plus",
    accent: "lime",
  },
  {
    slug: "citaclick",
    name: "CitaClick",
    category: "Servicios · Reservas",
    sector: "Servicios",
    status: "Producto digital",
    summary: "Solución de citas y reservas orientada a profesionales y empresas de servicios.",
    challenge: "Disminuir la fricción de coordinar horarios mediante conversaciones manuales y agendas dispersas.",
    solution: "Una experiencia de reservas en línea con disponibilidad, solicitudes y gestión de clientes.",
    features: ["Reservas en línea", "Disponibilidad", "Confirmaciones", "Gestión de clientes"],
    accent: "gold",
  },
  {
    slug: "mesaclick",
    name: "MesaClick",
    category: "Gastronomía · Experiencia digital",
    sector: "Comercio",
    status: "Experiencia para restaurantes",
    summary: "Plataforma para conectar mesas, menús y servicios digitales en restaurantes.",
    challenge: "Facilitar el acceso inmediato a información comercial y mejorar la interacción del cliente en el establecimiento.",
    solution: "Una experiencia móvil vinculada a la mesa mediante enlaces, QR o NFC, preparada para catálogos y promociones.",
    features: ["Menú digital", "Acceso por mesa", "Promociones", "Experiencia móvil"],
    url: "https://mesaclick.vercel.app/",
    image: "/projects/mesaclick.png",
    imageAlt: "Panel de gestión de restaurantes MesaClick",
    accent: "pink",
  },
  {
    slug: "lider-seguros-nfc",
    name: "Líder Seguros NFC",
    category: "Seguros · NFC y software",
    sector: "Seguros",
    status: "Ecosistema digital conectado",
    summary: "Llaveros NFC, portal para asegurados y administración de pólizas, asistencia y operación comercial.",
    challenge: "Mantener servicios, documentos y asistencia disponibles para el asegurado, mientras el equipo interno administra pólizas, canales, comisiones y renovaciones desde una sola plataforma.",
    solution: "Una solución integral que conecta llaveros NFC personalizados con una aplicación responsive y un panel administrativo adaptable a escritorio y dispositivos móviles.",
    features: ["Acceso mediante llavero NFC", "Aplicación para asegurados", "Panel administrativo responsive", "Pólizas y documentos", "Asistencia vial", "Renovaciones, canales y comisiones"],
    url: "https://lidersegurosadm.com/",
    image: "/media/lider/lider-keychain-car-hq.png",
    imageAlt: "Llavero NFC de Líder de Seguros junto a las llaves de un vehículo",
    accent: "cyan",
  },
  {
    slug: "lider-seguros-app",
    name: "Líder de Seguros App",
    category: "InsurTech · Aplicación para asegurados",
    sector: "Seguros",
    status: "En desarrollo",
    summary: "Aplicación móvil para controlar la póliza RCV, anticipar vencimientos, centralizar documentos y acompañar el cuidado del vehículo.",
    challenge: "Evitar que el asegurado pierda la vigencia de su póliza y reunir en una sola experiencia la información, los trámites y el acompañamiento que hoy dependen de canales dispersos.",
    solution: "Una app para iOS y Android que convierte la póliza en una experiencia activa: muestra su estado, anticipa renovaciones, organiza documentos y conecta asistencia, mantenimiento, siniestros y beneficios.",
    features: ["Póliza y renovación RCV", "Alertas de vencimiento", "Documentos digitales", "Vehículo y mantenimiento", "Reporte guiado de siniestros", "Integración con NFC"],
    image: "/projects/lider-seguros-app.png",
    imageAlt: "Concepto visual de la aplicación móvil para asegurados de Líder de Seguros",
    accent: "gold",
  },
  {
    slug: "elite-links",
    name: "Elite Links",
    category: "Movilidad · Portal inteligente",
    sector: "Movilidad",
    status: "Portal de servicios",
    summary: "Portal de servicios vehiculares, emergencias, aliados, documentos y recordatorios.",
    challenge: "Unificar accesos críticos y beneficios del conductor en una sola experiencia digital.",
    solution: "Un portal adaptable conectado por enlace o NFC con servicios, documentos y aliados organizados por prioridad.",
    features: ["Emergencias", "Aliados", "Documentos", "Mantenimiento", "Promociones"],
    url: "https://elite-links.vercel.app/",
    image: "/projects/elite-links.png",
    imageAlt: "Portal móvil de servicios vehiculares Elite Links",
    accent: "violet",
  },
  {
    slug: "guia-kupai",
    name: "Guía Kupai",
    category: "Comercio · Directorio digital",
    sector: "Comercio",
    status: "Directorio comercial",
    summary: "Directorio y guía digital para conectar consumidores con comercios y opciones gastronómicas.",
    challenge: "Facilitar el descubrimiento de negocios y organizar la oferta comercial por categorías.",
    solution: "Una guía móvil con navegación directa hacia comercios, categorías y propuestas disponibles.",
    features: ["Directorio", "Categorías", "Experiencia móvil", "Enlaces comerciales"],
    url: "https://guia.kupaifastfood.com/",
    image: "/projects/guia-kupai.png",
    imageAlt: "Guía digital de comercios Kupai",
    accent: "gold",
  },
  {
    slug: "credired",
    name: "CrediRed",
    category: "FinTech · Ventas y créditos",
    sector: "Comercio",
    status: "SaaS comercial",
    summary: "Sistema para controlar ventas, inventario, créditos, cobros y redes de distribuidores desde cualquier dispositivo.",
    challenge: "Dar visibilidad a operaciones comerciales que suelen vivir entre cuadernos, mensajes y hojas de cálculo dispersas.",
    solution: "Una plataforma multimoneda con inventario, ventas a crédito, abonos, recordatorios, jerarquías comerciales e indicadores en tiempo real.",
    features: ["Ventas y créditos", "Inventario", "Red multinivel", "Cobros y abonos", "Multimoneda", "Dashboard"],
    url: "https://credi-red.vercel.app/",
    accent: "lime",
  },
  {
    slug: "ventaclick",
    name: "VentaClick",
    category: "RetailTech · Inventario",
    sector: "Comercio",
    status: "Sistema de ventas",
    summary: "Gestión simple de tiendas, inventario, compras y ventas en una plataforma preparada para pequeños comercios.",
    challenge: "Reemplazar controles manuales por una herramienta cotidiana que no complique la operación del negocio.",
    solution: "Un sistema directo para registrar movimientos, mantener existencias visibles y tomar mejores decisiones comerciales.",
    features: ["Inventario", "Ventas", "Compras", "Gestión de tienda", "Acceso responsive"],
    url: "https://ventaclick-xi.vercel.app/",
    accent: "cyan",
  },
  {
    slug: "paycopy",
    name: "PayCopy",
    category: "FinTech · Enlaces de cobro",
    sector: "Finanzas",
    status: "Producto digital",
    summary: "Enlaces de cobro que organizan datos de Pago Móvil, Zelle, Binance y otros métodos para copiar cada dato con un toque.",
    challenge: "Eliminar errores y fricción al compartir instrucciones de pago por múltiples canales.",
    solution: "Una experiencia ligera y compartible que concentra métodos de pago y simplifica el paso de cobrar o pagar.",
    features: ["Enlaces de pago", "Pago Móvil", "Zelle y Binance", "Copiar con un toque", "Experiencia móvil"],
    url: "https://paycopy.app/",
    accent: "violet",
  },
  {
    slug: "dr-jackson-briones",
    name: "Dr. Jackson Briones",
    category: "Salud · Presencia profesional",
    sector: "Salud",
    status: "Sitio médico",
    summary: "Presencia digital para un especialista en urología, cirugía laparoscópica y robótica, con servicios, sedes y conversión a citas.",
    challenge: "Comunicar autoridad médica con claridad y convertir la búsqueda de información en una ruta directa hacia la consulta.",
    solution: "Un sitio editorial, rápido y orientado a pacientes que organiza especialidades, ubicaciones, proceso de atención y contacto.",
    features: ["Perfil profesional", "Servicios médicos", "Consultorios", "Agenda por WhatsApp", "SEO local"],
    url: "https://drbriones.com/",
    accent: "cyan",
  },
  {
    slug: "ads-restauro",
    name: "ADS Restauro",
    category: "Educación · Conversión digital",
    sector: "Educación",
    status: "Landing de formación",
    summary: "Experiencia de captación e inscripción para un programa de técnicas de restauración artística avanzada.",
    challenge: "Presentar una oferta educativa especializada, construir confianza y llevar al interesado hacia la reserva de su cupo.",
    solution: "Una landing narrativa con beneficios, equipo, trayectoria, inscripción y llamadas a la acción distribuidas por intención.",
    features: ["Landing page", "Programa formativo", "Equipo y trayectoria", "Captación", "Inscripción"],
    url: "https://adsrestauro.vercel.app/",
    accent: "pink",
  },
];
