import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title:"Nosotros", description:"Conoce la visión, el liderazgo y los principios de Zivi Dynamics C.A., empresa venezolana de desarrollo tecnológico.", alternates:{canonical:"/nosotros"} };

export default function AboutPage(){return <>
  <section className="pageHero about-position-hero"><div className="container"><span className="eyebrow">Zivi Dynamics C.A.</span><h1>Tecnología venezolana con visión de alcance mundial.</h1><p className="lead">Convertimos ideas y procesos empresariales en aplicaciones, plataformas, automatizaciones y experiencias digitales modernas.</p></div></section>
  <section className="positioning-section"><div className="container about-position-grid"><div className="about-brand-panel"><img src="/brand/zivi-logo-horizontal-full.svg" alt="Zivi Dynamics C.A. Soluciones Digitales" loading="lazy" decoding="async"/><div><span>Evolución dinámica</span><strong>Movimiento · innovación · conexión</strong></div></div><div><span className="eyebrow">Nuestra empresa</span><h2>Impulsamos la evolución digital de Venezuela.</h2><p>Zivi Dynamics C.A. es una empresa venezolana de desarrollo tecnológico especializada en aplicaciones móviles, plataformas web, sistemas empresariales, software a la medida, integraciones con inteligencia artificial y soluciones NFC.</p><p>Diseñamos ecosistemas digitales robustos, modernos y escalables para organizaciones que buscan automatizar procesos, optimizar operaciones y crecer con estándares internacionales.</p></div></div></section>
  <section className="team-position-section"><div className="container"><div className="positioning-head"><div><span className="eyebrow">Liderazgo y equipo</span><h2>Personas comprometidas con la transformación tecnológica.</h2></div><p>La dirección combina visión empresarial, comunicación directa y enfoque práctico para convertir necesidades en productos funcionales.</p></div><div className="team-position-grid"><article className="team-position-card primary"><div className="team-position-photo"><img src="/team/joswald-v2.webp" alt="Joswald Alejandro López Luna" loading="lazy" decoding="async"/></div><div><span>CEO y Fundador</span><h3>Joswald Alejandro López Luna</h3><blockquote>“La digitalización de Venezuela es una oportunidad para transformar empresas, instituciones y comunidades. Nuestra misión es hacer que la tecnología automatice cada sector, conecte procesos y multiplique oportunidades de crecimiento con soluciones de nivel mundial.”</blockquote><strong>Automatizar para avanzar.</strong></div></article><article className="team-position-card"><div className="team-position-photo"><img src="/team/herasi-v2.webp" alt="Herasi Silva" loading="lazy" decoding="async"/></div><div><span>Equipo de trabajo</span><h3>Herasi Silva</h3><p>Forma parte del equipo que acompaña la creación y evolución de soluciones innovadoras, aportando compromiso profesional, orientación al cliente y enfoque en resultados sostenibles.</p><strong>Innovación, colaboración y mejora continua.</strong></div></article></div></div></section>
  <section className="positioning-process"><div className="container value-position-grid"><article><span>01</span><h2>Misión</h2><p>Crear soluciones digitales que simplifiquen procesos, conecten personas y generen valor para cada organización.</p></article><article><span>02</span><h2>Visión</h2><p>Ser un referente venezolano en software, inteligencia artificial aplicada, HealthTech y tecnología NFC.</p></article><article><span>03</span><h2>Principio</h2><p>Construir tecnología útil, responsable y preparada para evolucionar con el negocio.</p></article><article><span>04</span><h2>Relación</h2><p>Trabajar con alcance claro, comunicación directa y acompañamiento profesional.</p></article></div></section>
  <section className="section"><div className="container cta"><div><span className="eyebrow">Construyamos juntos</span><h2>Una solución debe representar el futuro de tu organización.</h2></div><Link href="/contacto" className="btn">Solicitar una propuesta</Link></div></section>
</>}