import Link from "next/link";

const services=[
  ["📱","Apps móviles","Aplicaciones nativas y multiplataforma con experiencias rápidas e intuitivas."],
  ["🌐","Sitios web","Plataformas modernas, seguras, responsivas y optimizadas para posicionamiento."],
  ["⚙️","Sistemas empresariales","Herramientas robustas para administrar operaciones, usuarios, ventas, pagos y reportes."],
  ["</>","Software a la medida","Arquitecturas personalizadas que se adaptan a los procesos y objetivos del negocio."],
  ["🧠","Integraciones IA","Asistentes, automatizaciones, análisis y flujos inteligentes conectados con datos reales."],
  ["◉","Tecnología NFC","Tarjetas, llaveros y habladores conectados con experiencias digitales medibles."],
];
const projects=[
  ["HealthTech","Sociedad Venezolana de Urología","Ecosistema institucional, contenidos científicos y servicios para miembros."],
  ["Membresías","SoveuroApp","Colegiatura, pagos, eventos, tickets, QR y administración de afiliados."],
  ["Salud pública","ZoriApp","Gestión de jornadas masivas de despistaje de cáncer de próstata."],
  ["Consultorios","PaciGest Plus","Administración de pacientes, agendas y operación de consultorios."],
  ["NFC + seguros","Líder Seguros","Portal vehicular conectado a llaveros NFC y servicios de asistencia."],
  ["Gastronomía","MesaClick","Experiencia digital para restaurantes, mesas y atención comercial."],
];
const sectors=[["♡","Salud"],["▣","Sociedades profesionales"],["◇","Seguros"],["♨","Restaurantes y comercios"],["☆","Eventos"],["▥","Empresas"]];

export default function Home(){return <>
<section className="hero"><div className="heroGridPattern"/><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">Soluciones digitales inteligentes</span><h1>Tecnología que conecta, automatiza y <span className="gradient">transforma.</span></h1><p className="lead">Desarrollamos aplicaciones móviles, páginas web, sistemas empresariales, software a la medida, integraciones con inteligencia artificial y soluciones NFC para impulsar la evolución digital de Venezuela.</p><div className="actions"><Link className="btn" href="/portafolio">Ver proyectos →</Link><a className="btn secondary" href="https://wa.me/584127065848">Hablar por WhatsApp</a></div><div className="trust"><span>✓ Soluciones a la medida</span><span>✓ Tecnología segura</span><span>✓ Resultados medibles</span></div></div><div className="visual heroShowcaseVisual"><img className="heroShowcaseImage" src="/brand/zivi-hero-v2.webp" alt="Ecosistema tecnológico de Zivi Dynamics con aplicaciones móviles, plataformas web, inteligencia artificial y soluciones NFC" loading="eager" decoding="async"/></div></div></section>

<section className="section brandBlock"><div className="container brandPanel"><div className="brandAsset"><img src="/zivi-logo-light.png" alt="Zivi Dynamics C.A. Soluciones Digitales" loading="lazy" decoding="async"/></div><article><span className="eyebrow">Evolución dinámica</span><h2>Construimos ecosistemas digitales, no soluciones aisladas.</h2><p>Zivi Dynamics C.A. es una empresa venezolana de desarrollo tecnológico especializada en aplicaciones móviles, plataformas web, sistemas empresariales, software a la medida, integraciones con inteligencia artificial y soluciones NFC. Diseñamos ecosistemas digitales robustos, modernos y escalables para organizaciones que buscan automatizar procesos, optimizar operaciones y crecer con estándares internacionales.</p><Link className="textLink" href="/nosotros">Conocer nuestra visión →</Link></article></div></section>

<section className="section"><div className="container"><div className="sectionHead"><span className="eyebrow">Nuestras capacidades</span><h2>Un equipo para construir el ecosistema completo.</h2><p className="lead">Combinamos estrategia, experiencia de usuario, ingeniería de software y automatización para transformar operaciones reales.</p></div><div className="grid serviceGrid">{services.map(([i,t,d],n)=><article className="card" key={t}><span className="number">0{n+1}</span><div className="icon">{i}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

<section className="section leadership"><div className="container"><div className="sectionHead"><span className="eyebrow">Liderazgo y visión</span><h2>La tecnología debe elevar el potencial de cada sector.</h2><p className="lead">El propósito de Zivi nace en Venezuela y se proyecta hacia estándares de alcance mundial.</p></div><div className="teamGrid"><article className="profile primary"><div className="portrait"><img src="/team/joswald-v2.webp" alt="Joswald Alejandro López Luna" loading="lazy" decoding="async"/></div><div className="profileText"><span>CEO & Fundador</span><h3>Joswald Alejandro López Luna</h3><blockquote>“Creemos que la digitalización de Venezuela es una oportunidad para transformar empresas, instituciones y comunidades. Nuestra misión es hacer que la tecnología automatice cada sector, conecte procesos y multiplique oportunidades de crecimiento con soluciones de nivel mundial.”</blockquote><strong>Automatizar para avanzar.</strong></div></article><article className="profile"><div className="portrait"><img src="/team/herasi-v2.webp" alt="Herasi Silva" loading="lazy" decoding="async"/></div><div className="profileText"><span>Equipo de trabajo</span><h3>Herasi Silva</h3><p>Comprometido con el desarrollo de soluciones innovadoras y la evolución tecnológica de nuestros clientes, aportando una visión profesional orientada a resultados y crecimiento sostenible.</p><strong>Innovación aplicada al cliente.</strong></div></article></div></div></section>

<section className="section vision"><div className="visionPattern"/><div className="container visionGrid"><div><span className="eyebrow">Nuestra visión</span><h2>Digitalizar Venezuela con tecnología de alto nivel.</h2><p className="lead">Impulsamos una visión donde cada organización en Venezuela pueda acceder a herramientas digitales de alto nivel para ser más eficiente, competitiva y sostenible. En Zivi Dynamics creemos en la innovación aplicada, en la automatización inteligente y en el poder del desarrollo tecnológico para elevar los estándares del país al nivel de los mejores del mundo.</p><div className="visionPills"><span>Automatización inteligente</span><span>Visión global</span><span>Calidad profesional</span></div></div><div className="globe">◎<i/><i/><i/><small>Tecnología para transformar sectores</small></div></div></section>

<section className="section"><div className="container"><div className="sectionHead"><span className="eyebrow">Portafolio</span><h2>Productos que resuelven problemas reales.</h2></div><div className="grid">{projects.map(([tag,name,desc])=><Link href="/portafolio" className="card project" key={name}><span className="tag">{tag}</span><h3>{name}</h3><p>{desc}</p><strong>Ver proyecto →</strong></Link>)}</div></div></section>

<section className="section alt"><div className="container"><div className="sectionHead centered"><span className="eyebrow">Sectores que impulsamos</span><h2>Tecnología alineada con cada industria.</h2></div><div className="sectorGrid">{sectors.map(([i,t])=><div key={t}><span>{i}</span><b>{t}</b></div>)}</div></div></section>

<section className="section"><div className="container cta"><div><span className="eyebrow">Construyamos el próximo producto</span><h2>¿Listo para transformar tu organización?</h2><p>Conversemos sobre cómo automatizar procesos, conectar servicios y crear una experiencia digital de alto nivel.</p></div><div className="actions"><a className="btn" href="https://wa.me/584127065848">Hablar por WhatsApp</a><Link className="btn secondary" href="/contacto">Solicitar propuesta</Link></div></div></section>
</>}