import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title:"Tecnología NFC para empresas", description:"Tarjetas, llaveros, credenciales y habladores NFC conectados con portales digitales, documentos, servicios y analítica.", alternates:{canonical:"/nfc"} };
const products=[["Tarjetas NFC","Presentación, identificación, membresías, catálogos y perfiles digitales."],["Llaveros inteligentes","Pólizas, asistencia, documentos, mantenimiento y servicios vehiculares."],["Habladores NFC","Menús, reseñas, promociones, Wi-Fi y acciones desde mesas o mostradores."],["Credenciales conectadas","Identidad, validación, control de acceso y consulta de información."]];
const uses=[["Conectar","El usuario acerca su teléfono sin instalar una aplicación."],["Abrir","Se activa un portal o acción digital configurada para el producto."],["Actualizar","El contenido puede evolucionar sin reemplazar el dispositivo físico."],["Medir","Las interacciones pueden integrarse con analítica y procesos internos."]];

export default function NfcPage(){return <>
  <section className="pageHero nfc-position-hero"><div className="container"><span className="eyebrow">Tecnología NFC</span><h1>Conecta objetos físicos con experiencias digitales.</h1><p className="lead">Diseñamos el producto, el portal y la lógica necesaria para convertir una interacción por proximidad en una acción útil y medible.</p><div className="nfc-demo"><div className="nfc-device"><span>Z</span><i/><i/><i/></div><div><small>Interacción inmediata</small><strong>Acerca el teléfono. Abre la experiencia.</strong></div></div></div></section>
  <section className="positioning-section"><div className="container product-position-grid">{products.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h2>{title}</h2><p>{text}</p><Link href="/contacto">Cotizar producto →</Link></article>)}</div></section>
  <section className="positioning-process"><div className="container"><div className="positioning-head"><div><span className="eyebrow">Cómo funciona</span><h2>Hardware, contenido y software dentro del mismo sistema.</h2></div><p>La tarjeta o el llavero es el punto de acceso. El verdadero valor está en la experiencia digital y en los procesos que se activan.</p></div><div className="positioning-steps">{uses.map(([title,text],index)=><div key={title}><span>0{index+1}</span><strong>{title}</strong><p>{text}</p></div>)}</div></div></section>
  <section className="positioning-section"><div className="container positioning-split"><div><span className="eyebrow">Aplicaciones</span><h2>Un mismo dispositivo puede resolver necesidades diferentes.</h2></div><div className="use-list"><span>Perfiles y tarjetas de presentación</span><span>Menús y catálogos comerciales</span><span>Pólizas y asistencia vehicular</span><span>Identificación y membresías</span><span>Fidelización y promociones</span><span>Documentos y servicios internos</span></div></div></section>
  <section className="section"><div className="container cta"><div><span className="eyebrow">Proyecto NFC</span><h2>Diseñemos el producto físico y la plataforma que lo hace útil.</h2></div><Link href="/contacto" className="btn">Solicitar cotización NFC</Link></div></section>
</>}
